#!/bin/sh
# ---------------------------------------------
# Bootstrap file to initialize a new environment
# ---------------------------------------------

# I have (3) primary environments:
# - Mac (default): standard set of both cli and gui tools installed
# - Mac (full): complete install of my working environment
# - Linux (default): standard set of cli tools

# Get the current OS (expecting "Darwin" or "Linux")
export OS_TYPE="$(uname -s)"
echo "I found I'm running on: ${OS_TYPE}"

# Check what type of machine this will be (DEFAULT or FULL)
# TODO: setup a prompt for input from the user (with a default setting to lite)

while true; do
    echo "Will this be a default install or a full install? (default/full)"
    read -r INSTALL_TYPE

    case "$INSTALL_TYPE" in
        default)
            BOOTSTRAP_MODE="default"
            break
            ;;
        full)
            BOOTSTRAP_MODE="full"
            break
            ;;
        *)
            echo "Invalid input. Please type 'default' or 'full'."
            ;;
    esac
done

echo "BOOTSTRAP_MODE is set to $BOOTSTRAP_MODE"
